default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: lib_development


test:
  <<: *default
  database: lib_test

production:
  <<: *default
  database: lib_production
